# Generated by Django 4.2.2 on 2023-07-12 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noticia',
            old_name='fecha_de_publicacion',
            new_name='fecha_publicacion',
        ),
        migrations.AlterField(
            model_name='noticia',
            name='resumen',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='titulo',
            field=models.CharField(max_length=50),
        ),
    ]
