# Generated by Django 4.2.3 on 2023-07-21 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='description',
            new_name='descripcion',
        ),
    ]
