# Generated by Django 4.2.3 on 2023-07-24 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0002_rename_description_categoria_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='categoria_articulo',
            field=models.ForeignKey(default='Sin categoría', null=True, on_delete=django.db.models.deletion.SET_NULL, to='articulos.categoria'),
        ),
    ]
