# Generated by Django 4.2.2 on 2023-07-24 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0003_alter_articulo_categoria_articulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo',
            name='usuario_articulo',
        ),
    ]
