# Generated by Django 4.2.2 on 2023-07-24 23:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articulos', '0004_remove_articulo_usuario_articulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='usuario_articulo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
