# Generated by Django 4.2.3 on 2023-07-21 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('publico', 'Publico'), ('colaborador', 'Colaborador')], default='publico', max_length=11),
        ),
    ]
